name: Auto Merge CDN
on:
  push:
    branches:
      - 'cdn/*'

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: merge-branch
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ github.ref_name }}
          target_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete origin branch
        if: success()
        run: |
          echo "Merging successful, deleting branch ${{ github.ref_name }}..."
          gh api -X DELETE /repos/${{ github.repository }}/git/refs/heads/${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}