name: Auto Merge CDN
on:
  push:
    branches:
      - 'cdn/*'

permissions:
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge and Delete
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          BRANCH_NAME="${{ github.ref_name }}"
          
          git checkout main
          git pull origin main
          
          if git merge "origin/$BRANCH_NAME"; then
            git push origin main
            git push origin --delete "$BRANCH_NAME" || true
          else
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}